### ISSUE TITLE
How to detect call has ended

### ISSUE THREAD

**Issue by harshapulikollu** [Apurv2017/PhoneCallState#1]
I want to how to use this plugin to know when users discounts the call after talking.will it work even app is terminated (not in background)
If it's not possible then please provide we any workaround. Thanks in advance.

**Comment by karthikcfs** [comment]
It will work for incoming call only. I need both an incoming and outgoing call. Can you help with this?

**Comment by harshapulikollu** [comment]
> 
> 
> It will work for incoming call only. I need both an incoming and outgoing call. Can you help with this?

For android I wrote a native phone listener service which will detect ringing, on call and disconnection of call.
