### ISSUE TITLE
apk buil error

### ISSUE THREAD

**Issue by akhilprogrammer** [Apurv2017/PhoneCallState#5]
![Screenshot from 2020-04-07 01-58-53](https://user-images.githubusercontent.com/39589942/78602505-304b4480-7874-11ea-9bda-a260faa84a55.png)
![Screenshot from 2020-04-07 01-59-04](https://user-images.githubusercontent.com/39589942/78602510-32150800-7874-11ea-8452-5fc3874907aa.png)

**Comment by Abhishek01039** [comment]
Migrate to AndroidX 
may be solved your Problem

**Comment by akhilprogrammer** [comment]
open the plugin source file and go to

android/build.gardle

then change compileSdkVersion 27   to compileSdkVersion 28
